solutions = [
      { "name"        : "25.0.1364.84",
        "url"         : "https://src.chromium.org/chrome/releases/25.0.1364.84",
        "deps_file"   : "DEPS",
        "managed"     : True,
        "custom_deps" : {
            "build": None,
            "build/scripts/command_wrapper/bin": None,
            "build/scripts/gsd_generate_index": None,
            "build/scripts/private/data/reliability": None,
            "build/third_party/gsutil": None,
            "build/third_party/lighttpd": None,
            "build/third_party/swarm_client": None,
            "commit-queue": None,
            "depot_tools": None,
            "chromeos": None,

            "src/third_party/WebKit/LayoutTests": None,
            "src/content/test/data/layout_tests/LayoutTests": None,
            "src/chrome/tools/test/reference_build/chrome_win": None,
            "src/chrome_frame/tools/test/reference_build/chrome_win": None,
            "src/chrome/tools/test/reference_build/chrome_linux": None,
            "src/chrome/tools/test/reference_build/chrome_mac": None,
            "src/third_party/hunspell_dictionaries": None,
            "src/native_client": None,

            "src/chrome/test/data/extensions/api_test/permissions/nacl_enabled/bin": None,
            "src/chrome/test/data/perf/canvas_bench": None,
            "src/chrome/test/data/perf/frame_rate/content": None,
            "src/content/test/data/layout_tests/LayoutTests/fast/events": None,
            "src/content/test/data/layout_tests/LayoutTests/fast/filesystem/resources": None,
            "src/content/test/data/layout_tests/LayoutTests/fast/js/resources": None,
            "src/content/test/data/layout_tests/LayoutTests/fast/workers": None,
            "src/content/test/data/layout_tests/LayoutTests/http/tests/appcache": None,
            "src/content/test/data/layout_tests/LayoutTests/http/tests/resources": None,
            "src/content/test/data/layout_tests/LayoutTests/http/tests/websocket/tests": None,
            "src/content/test/data/layout_tests/LayoutTests/http/tests/workers": None,
            "src/content/test/data/layout_tests/LayoutTests/http/tests/xmlhttprequest": None,
            "src/content/test/data/layout_tests/LayoutTests/media": None,
            "src/content/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/events": None,
            "src/content/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/workers": None,
            "src/content/test/data/layout_tests/LayoutTests/platform/chromium-win/http/tests/workers": None,
            "src/content/test/data/layout_tests/LayoutTests/platform/chromium-win/storage/domstorage": None,
            "src/content/test/data/layout_tests/LayoutTests/platform/chromium/fast/events": None,
            "src/content/test/data/layout_tests/LayoutTests/platform/chromium/fast/workers": None,
            "src/content/test/data/layout_tests/LayoutTests/storage/domstorage": None,
            "src/content/test/data/layout_tests/LayoutTests/storage/indexeddb": None,
            "src/third_party/safe_browsing/testing": None,
            "src/third_party/webgl_conformance": None,

            "src/third_party/nacl_sdk_binaries": None,
            "src/sandbox/linux/seccomp-legacy": None,
            "src/third_party/swig/win": None,
            "src/chrome/test/data/perf/third_party/octane": None,
            "src/third_party/webdriver/pylib": None,
            "src/third_party/libphonenumber/src/phonenumbers": None,
            "src/third_party/pyftpdlib/src": None,
            "src/third_party/xulrunner-sdk": None,
            "src/webkit/media/crypto/ppapi/cdm": None,
            "src/tools/deps2git": None,
            "src/third_party/bidichecker": None,
            "src/third_party/undoview": None,
            "src/third_party/lighttpd": None,
            "src/tools/page_cycler/acid3": None,
            "src/third_party/gnu_binutils": None,
            "src/third_party/mingw-w64/mingw/bin": None,
            "src/third_party/WebKit/Tools/DumpRenderTree": None,
            "src/third_party/hunspell": None,
            "src/third_party/syzygy/binaries": None,
            "src/third_party/pefile": None,
            "src/third_party/cacheinvalidation/src": None,
            "src/tools/swarm_client": None,
            "src/third_party/accessibility-developer-tools": None,
            "src/third_party/libexif/sources": None,
            "src/content/test/data/layout_tests/LayoutTests/fast/files": None,
            "src/third_party/libphonenumber/src/resources": None,
            "src/third_party/snappy/src": None,
            "src/third_party/pywebsocket/src": None,
            "src/third_party/scons-2.0.1": None,
            "src/third_party/webpagereplay": None,
            "src/third_party/libphonenumber/src/test": None,
            "src/third_party/WebKit/Tools/Scripts": None,
            "src/third_party/pymox/src": None,
            "src/third_party/trace-viewer": None,
            "src/third_party/swig/Lib": None,
            "src/third_party/WebKit/Tools/TestWebKitAPI": None,
        },
        "safesync_url": "",
    },
]
